---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

workspace:
  path: /drone/src

volumes:
  - name: cache
    temp: { }
  - name: dist
    temp: { }

environment:
  NPM_CONFIG_CACHE: /cache/npm/cache

steps:
  - name: deps
    image: node:16.15.0
    volumes:
      - name: cache
        path: /cache
    commands:
      - yarn install

  - name: test
    image: node:16.15.0
    volumes:
      - name: cache
        path: /cache
      - name: dist
        path: /drone/src/dist
    commands:
      - yarn test
    depends_on:
      - deps
  
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: cicd
      link_names: true
      template: >
        {{#success build.status}}
          The {{ repo.owner }}/{{ repo.name }} build <{{ build.link }}| {{build.number}} ↗> is succeeded! Thanks <@{{build.author}}>
        {{else}}
          The {{ repo.owner }}/{{ repo.name }} build <{{ build.link }}| {{build.number}} ↗> is broken! Blame <@{{build.author}}>
        {{/success}}
    depends_on:
      - test
    when:
      status: [ success, failure ]
